apps/myApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^travels/trip_add$', views.trip_add, name='trip_add'),
    url(r'^travels/add$', views.travels_add, name='travels_add'),
    url(r'^travels/destination/(?P<id>\d+)$', views.travels_destination, name='travels_destination'),
    url(r'^travels/join/(?P<id>\d+)$', views.trip_join, name='trip_join'),
    url(r'^travels$', views.travels, name='travels')
]

myServer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.myApp.urls', namespace='myApp')),
]

apps/myApp/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import datetime

# Create your models here.

class TripManager(models.Manager):
    def add(self, form_data, user_id):
        error_list = []
        is_valid = True
        today = datetime.datetime.today()

        if len(form_data['destination']) == 0:
            error_list.append("Please add a destination")
            is_valid = False
        if len(form_data['description']) == 0:
            error_list.append("Please add a description")
            is_valid = False

        try:
            from_date = datetime.datetime.strptime(form_data['from_date'], '%m/%d/%Y')
        except ValueError:
            error_list.append("Please enter a valid from date")
            is_valid = False

        try:
            to_date = datetime.datetime.strptime(form_data['to_date'], '%m/%d/%Y')
        except ValueError:
            error_list.append("Please enter a valid to date")
            is_valid = False

        if from_date < today or to_date < today:
            error_list.append("All dates must be in the future")
            is_valid = False

        if to_date < from_date:
            error_list.append("From date must be before to date")
            is_valid = False

        if is_valid:

            # add trip data with one to many user as the 'planner'
            new_trip = self.create(destination = form_data['destination'], description = form_data['description'], to_date = to_date, from_date = from_date, user_id = user_id)

            # add user to the many to many table
            new_trip.users.add(user_id)

            return (is_valid, new_trip)
        else:
            return (is_valid, error_list)

        return true

    def join(self, trip_id, user_id):
        trip = Trip.objects.get(id=trip_id)
        if trip:
            trip.users.add(user_id)
            return trip
        else:
            return False

class UserManager(models.Manager):
    def register(self, form_data):
        error_list = []
        is_valid = True

        if len(form_data['name']) < 3:
            error_list.append("Name must be 3 or more characters long!")
            is_valid = False
        if len(form_data['username']) < 3:
            error_list.append("Username must be 3 or more characters long!")
            is_valid = False
        if len(form_data['password']) < 8:
            error_list.append("Password must be at least 8 or more characters long!")
            is_valid = False
        if form_data['password'] != form_data['password_confirm']:
            error_list.append("Passwords do not match!")
            is_valid = False
        if User.objects.filter(username = form_data['username']):
            error_list.append("This Username already exists!")
            is_valid = False

        if is_valid:
            hashed_password = bcrypt.hashpw(form_data['password'].encode(), bcrypt.gensalt())
            new_user = self.create(name = form_data['name'], username = form_data['username'], pw_hash = hashed_password)
            return (is_valid, new_user)
        else:
            return (is_valid, error_list)

    def login(self, form_data):
        error_list = []

        if len(form_data['username']) == 0:
            error_list.append("Please enter a username")

        if len(form_data['password']) == 0:
            error_list.append("Please enter a password")

        user = User.objects.filter(username = form_data['username'])

        if user:
            user = user[0]
            if bcrypt.checkpw(form_data['password'].encode(), user.pw_hash.encode()):
                # Returning user object to views
                return (True, user)
        else:
            error_list.append("Username or password is incorrect")

        return (False, error_list)


class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class Trip(models.Model):
    destination = models.CharField(max_length=255)
    description = models.TextField()
    to_date = models.DateTimeField()
    from_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(User, related_name="all_trips")
    user = models.ForeignKey(User, related_name="trip")
    objects = TripManager()

apps/myApp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import *

# Create your views here:
def index(request):
    return render(request, 'myApp/index.html')

def register(request):
    if request.method != 'POST':
        return redirect(reverse('myApp:index'))

    validation = User.objects.register(request.POST)
    if validation[0] == False:
        #errors!
        for error in validation[1]:
            messages.error(request, error)
        return redirect(reverse('myApp:index'))
    else:
        #no errors!
        messages.success(request, "Welcome, {}. You have successfully registered!".format(validation[1].name))
        request.session['user_id'] = validation[1].id
        return redirect(reverse('myApp:travels'))

def login(request):
    if request.method != 'POST':
        return redirect(reverse('myApp:index'))

    validation = User.objects.login(request.POST)
    print validation[0]
    if validation[0] == False:
        #errors!
        for error in validation[1]:
            messages.error(request, error)
        return redirect(reverse('myApp:index'))
    else:
        #no errors!
        messages.success(request, "Welcome, {}. You have successfully logged in!".format(validation[1].name))
        request.session['user_id'] = validation[1].id
        return redirect(reverse('myApp:travels'))


def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']
        messages.success(request, "You have successfully logged out")
        return redirect(reverse('myApp:index'))
    else:
        messages.error(request, "You were not logged in")
        return redirect(reverse('myApp:index'))

## travel routes below!!

def travels(request):
    if not 'user_id' in request.session:
        messages.error(request, 'You must log in!')
        return redirect('myApp:index')

    myTrips = Trip.objects.filter(users__id__in=[request.session['user_id']])
    otherTrips = Trip.objects.exclude(users__id__in=[request.session['user_id']])
    context = {
        'myTrips': myTrips,
        'otherTrips': otherTrips
    }
    return render(request, 'myApp/travels.html', context)

def travels_add(request):
    if not 'user_id' in request.session:
        messages.error(request, 'You must log in!')
        return redirect('myApp:index')
    return render(request, 'myApp/travels_add.html')

def travels_destination(request, id):
    if not 'user_id' in request.session:
        messages.error(request, 'You must log in!')
        return redirect('myApp:index')

    trip = Trip.objects.get(id=id)
    otherUsers = User.objects.filter(all_trips__id__in=[trip.id]).exclude(id__in=[request.session['user_id']])

    context = {
        'trip': trip,
        'otherUsers': otherUsers
    }

    return render(request, 'myApp/travels_destination.html', context)


def trip_add(request):
    if not 'user_id' in request.session:
        messages.error(request, 'You must log in!')
        return redirect('myApp:index')
    if request.method != 'POST':
        return redirect(reverse('myApp:travels_add'))

    validation = Trip.objects.add(request.POST, request.session['user_id'])
    if validation[0] == False:
        #errors!
        for error in validation[1]:
            messages.error(request, error)
        return redirect(reverse('myApp:travels_add'))
    else:
        messages.success(request, "Your trip has been added!")
        return redirect(reverse('myApp:travels'))

def trip_join(request, id):
    if not 'user_id' in request.session:
        messages.error(request, 'You must log in!')
        return redirect('myApp:index')
    if request.method != 'GET':
        return redirect(reverse('myApp:travels'))

    validation = Trip.objects.join(id, request.session['user_id'])

    if validation == False:
        messages.error('Something went wrong :( Try again.')
    else:
        messages.success(request, "You have joined a trip to {}".format(validation.destination))


    return redirect(reverse('myApp:travels'))

apps/myApp/templates/myApp/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Login/Register</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'myApp/css/stylesheet.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
      <div class="wrapper row">
      <div class="row">
        <div class="col-xs-12 text-center">
          <h1> Welcome! </h1>
        </div>
      </div>

      {% if messages %}
          {% for message in messages %}
              <div class='alert alert-{{message.tags}}'>{{message}}</div>
          {% endfor %}
      {% endif %}

        <div class="col-md-6">
            <form class="" action="{% url 'myApp:register' %}" method="POST">
                {% csrf_token %}
                <h2>Register</h2>
                <div class="form-group">
                 <label for="first_name">Name</label>
                   <input name="name" type="text" class="form-control" id="" placeholder="">
                </div>

                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" class="form-control" id="" placeholder="" name="username">
                </div

                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input name="password" type="password" class="form-control" id="" placeholder="">
                  <p id="passwordHelpBlock" class="form-text text-muted">
                    Your password should be at least 8 characters long.
                  </p>
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword2">Confirm Password</label>
                  <input name="password_confirm" type="password" class="form-control" id="" placeholder="">
                </div>

                <button type="submit" name="register" class="btn btn-default">Register</button>
            </form>
        </div>

        <div class="col-md-6">

            <form class="" action="{% url 'myApp:login' %}" method="POST">
              <h2>Login</h2>
                {% csrf_token %}

                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" class="form-control" id="" placeholder="" name="username">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input name="password" type="password" class="form-control" id="" placeholder="">
                </div>

                <button type="submit" name="login" class="btn btn-default">Login</button>
            </form>
        </div>

      </div>
    </body>
</html>

apps/myApp/templates/myApp/travels.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Travel Dashboard</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'myApp/css/stylesheet.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>
    <body>
      <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">Travel Dashboard</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'myApp:logout' %}">Logout</a></li>
              </ul>
            </div>
          </div>
        </nav>

      <div class="wrapper row">
        {% if messages %}
            {% for message in messages %}
                <div class='alert alert-{{message.tags}}'>{{message}}</div>
            {% endfor %}
        {% endif %}

        <h3>Your Trip Schedules</h3>
        <table class="table table-bordered">
          <thead>
            <th>Destination</th>
            <th>Travel Start Date</th>
            <th>Travel End Date</th>
            <th>Plan</th>
          </thead>

          <tbody>
          {% for trip in myTrips %}
            <tr class="active">
              <td class="active"><a href="{% url 'myApp:travels_destination' id=trip.id %}">{{trip.destination}}</a></td>
              <td class="active">{{trip.from_date|date:"M d, Y"}}</td>
              <td class="active">{{trip.to_date|date:"M d, Y"}}</td>
              <td class="active">{{trip.description}}</td>

            </tr>
          {% endfor %}
          </tbody>
        </table>

        <h3>Other User's Travel Plans</h3>
        <table class="table table-bordered">
        <thead>
          <th>Name</th>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Plan</th>
          <th>Do you want to join?</th>
        </thead>

        <tbody>
        {% for trip in otherTrips %}
          <tr class="active">
            <td class="active">{{trip.user.name}}</td>
            <td class="active"><a href="{% url 'myApp:travels_destination' id=trip.id %}">{{trip.destination}}</a></td>
            <td class="active">{{trip.from_date|date:"M d, Y"}}</td>
            <td class="active">{{trip.to_date|date:"M d, Y"}}</td>
            <td class="active">{{trip.description}}</td>
            <td class="active"><a href="{% url 'myApp:trip_join' id=trip.id %}">Join</a></td>
          </tr>
        {% endfor %}
        </tbody>
        </table>
        <a class="pull-right" href="{% url 'myApp:travels_add' %}">Add Travel Plan</a>
      </div>
    </body>
</html>

apps/myApp/templates/myApp/travels_add.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Add Plan</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'myApp/css/stylesheet.css' %}"media="screen" title="no title"  charset="utf-8">

        <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

        <!-- Added for Date Range Picker -->
        <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
    </head>
    <body>
      <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">Travel Dashboard</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'myApp:travels' %}">Home</a></li>
                <li><a href="{% url 'myApp:logout' %}">Logout</a></li>
              </ul>
            </div>
          </div>
        </nav>

      <div class="wrapper row">

        {% if messages %}

            {% for message in messages %}
                <div class='alert alert-{{message.tags}}'>{{message}}</div>
            {% endfor %}

        {% endif %}

        <div class="col-md-6">

            <form class="" action="{% url 'myApp:trip_add' %}" method="POST">
                {% csrf_token %}
                <h2>Add a Trip</h2>
                <div class="form-group">
                 <label for="destination">Destination</label>
                   <input name="destination" type="text" class="form-control" id="" placeholder="">
                </div>

                <div class="form-group">
                  <label for="description">Description</label>
                  <textarea class="form-control" rows="3" name="description"></textarea>

                </div>

                <div class="form-group"> <!-- Date input -->
                  <label class="control-label" for="from_date">Travel Date From</label>
                  <input class="form-control" id="from_date" name="from_date" placeholder="" type="text"/>
                </div>

                <div class="form-group"> <!-- Date input -->
                  <label class="control-label" for="to_date">Travel Date To</label>
                  <input class="form-control" id="to_date" name="to_date" placeholder="" type="text"/>
                </div>
                <button type="submit" name="add_trip" class="btn btn-default">Add</button>
            </form>
        </div>

      </div>
      <script>
        $('input[name="to_date"]').daterangepicker({
          singleDatePicker: true,
          showDropdowns: true
        });

        $('input[name="from_date"]').daterangepicker({
          singleDatePicker: true,
          showDropdowns: true
        });

      </script>
    </body>
</html>

apps/myApp/templates/myApp/travels_destination.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Destination</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'myApp/css/stylesheet.css' %}"media="screen" title="no title"  charset="utf-8">
    </head>

    <body>
      <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">Travel Dashboard</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'myApp:travels' %}">Home</a></li>
                <li><a href="{% url 'myApp:logout' %}">Logout</a></li>
              </ul>
            </div>
          </div>
        </nav>
      <div class="wrapper row">
        {% if messages %}
            {% for message in messages %}
                <div class='alert alert-{{message.tags}}'>{{message}}</div>
            {% endfor %}
        {% endif %}

        <h2>{{trip.destination}}</h2>
        <br/>
        Planned by: {{trip.user.name}}
        <br/>
        Description: {{trip.description}}
        <br/>
        Travel Date From: {{trip.from_date|date:"M d, Y"}}
        <br/>
        Travel Date To: {{trip.to_date|date:"M d, Y"}}
        <br/>
        <br/>

        {% if otherUsers %}

            <h3>Other users' joining the trip</h3>
            {% for user in otherUsers %}
                <div>{{user.name}}</div>
            {% endfor %}

        {% endif %}

      </div>
    </body>
</html>